img_path = "data/t2.jpg"
device = "cuda"
model = "EDSR"
shave = 10
scale = 4
single_patch_batch_size_start = 1
end_patch_dimension = 269
start_patch_dimension = 40
dim_gap = 1
run = 3
single_patch_dimension = 45
