img_path = 'data/test2.jpg'
device = 'cuda'
model = 'EDSR'
shave = 10
scale = 4
single_patch_batch_size_start = 10 #  starting batch size for a patch

# maximum valid batch size check in dimension range
end_patch_dimension = 50 # stop checking at this dimension
start_patch_dimension = 40 # start checking from this dimension
dim_gap = 1 # gap between dimension to dimension for iterative process

# single patch dimension all possible batch details
run = 3
single_patch_dimension = 45 # fixed dimension of a single patch


