img_path = "data/test5.jpg"
device = "cuda"
model = "EDSR"
shave = 10
scale = 4
single_patch_batch_size_start = 1
end_patch_dimension = 262
start_patch_dimension = 45
dim_gap = 1
run = 1
single_patch_dimension = 45
