img_path = "data/test2.jpg"
device = "cuda"
model = "EDSR"
shave = 10
scale = 4
single_patch_batch_size_start = 10
end_patch_dimension = 50
start_patch_dimension = 45
dim_gap = 1
run = 3
single_patch_dimension = 45
