img_path = "data/slices/1.npz"
device = "cuda"
model = "RRDB"
shave = 10
scale = 4
single_patch_batch_size_start = 1
end_patch_dimension = 169
start_patch_dimension = 40
dim_gap = 4
run = 1
single_patch_dimension = 45
