run = 10
last_folder = "Fri_Jun_4_15_36_01_2021"
last_stat_csv = "total_stat_Fri_Jun_4_15_36_03_2021"
img_height = 100
img_width = 100
shave = 10
dimension = 40
scale = 4
start_shave = 3
rrdb_path = "saved_models/rrdb_gen_500.pt"
max_dim = 390
