[batch_range_experiment]
status = "finished"
temp_file_name = "results/batch_forward_chop_experiment/Fri_Jul_9_13_05_18_2021/temp_maximum_batch_size_per_dimension.csv"
folder_name = "results/batch_forward_chop_experiment/Fri_Jul_9_13_05_18_2021"
last_patch_dim = 40
min_dim = 40
last_valid_batch = 92
shave = 10
scale = 4
dim_gap = 2
model_name = "EDSR"
device = "cuda"
img_path = "data/test5.jpg"
