[batch_range_experiment]
status = "finished"
temp_file_name = "results/batch_forward_chop_experiment/Tue_Aug_3_12_33_39_2021/temp_maximum_batch_size_per_dimension.csv"
folder_name = "results/batch_forward_chop_experiment/Tue_Aug_3_12_33_39_2021"
last_patch_dim = 40
min_dim = 40
last_valid_batch = 57
shave = 10
scale = 4
dim_gap = 4
model_name = "RRDB"
device = "cuda"
img_path = "data/slices/11.npz"
