[batch_range_experiment]
status = "finished"
temp_file_name = "results/batch_forward_chop_experiment/Tue_Jul_6_17_56_31_2021/temp_maximum_batch_size_per_dimension.csv"
folder_name = "results/batch_forward_chop_experiment/Tue_Jul_6_17_56_31_2021"
last_patch_dim = 50
min_dim = 40
last_valid_batch = 1
shave = 10
scale = 4
dim_gap = 4
model_name = "EDSR"
device = "cuda"
img_path = "data/test2.jpg"
